### ISSUE TITLE
Manager/Admin --- E-mail All

### ISSUE THREAD

**Issue by monalithatte** [sachinsawant71/magnolia-maintenance#26]
Add Attachment function is disabled while trying to send mail but it is picking up already files in system.

**Comment by sachinsawant71** [comment]
You pick up the attachment and add it to the email you are sending. It is disabled initially as no attachment selected. Button becomes enabled when user has selected attachment.

**Comment by monalithatte** [comment]
![image](https://cloud.githubusercontent.com/assets/16622344/12879653/71c7c9e0-ce5c-11e5-9fce-c1321d719f90.png)

Please check this added attachement when step 1 --- select from the dropdown --- Email To, step 2 --- To fill the Subject , step 3 --- Fill in the text box , step 4 --- Add Attachement dropdown box is selected (is empty does not allow to browse new file from machine, had to clear the cache as it was showing earler files only) and ADD button is not getting enabled.

Kindly recheck this case.

**Comment by monalithatte** [comment]
pl check the more info in github for this case.

**Comment by monalithatte** [comment]
![image](https://cloud.githubusercontent.com/assets/16622344/12879653/71c7c9e0-ce5c-11e5-9fce-c1321d719f90.png)

Please check this added attachement when step 1 --- select from the dropdown --- Email To, step 2 --- To fill the Subject , step 3 --- Fill in the text box , step 4 --- Add Attachement dropdown box is selected (is empty does not allow to browse new file from machine, had to clear the cache as it was showing earler files only) and ADD button is not getting enabled.

Kindly recheck this case.
